version: '3.8'

services:
  landing-page:
    image: ghcr.io/orakysec/do-lead-ao-lucro:latest
    container_name: do-lead-ao-lucro
    restart: always
    networks:
      - YkaroNET
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.doleadaolucro.rule=Host(`wandersonbuarque.com.br`)"
      - "traefik.http.routers.doleadaolucro.entrypoints=websecure"
      - "traefik.http.routers.doleadaolucro.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.doleadaolucro.loadbalancer.server.port=80"

networks:
  YkaroNET:
    external: true
